### ISSUE TITLE
'product' property mismatch with example

### ISSUE THREAD

**Issue by Jona630** [suchipi/switch-joy-con#1]
Hi !

In the Usage section it is expected to receive two devices as follows

`// [
//   {
//     vendorId: 1406,
//     productId: 8198,
//     path: 'IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/IOBluetoothHIDDriver',
//     serialNumber: '94-58-cb-a6-1b-86',
//     manufacturer: 'Unknown',
//     product: 'Joy-Con (L)',
//     release: 1,
//     interface: -1,
//     usagePage: 1,
//     usage: 5,
//     open: [Function: open]
//   },
//   {
//     vendorId: 1406,
//     productId: 8199,
//     path: 'IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/IOBluetoothHIDDriver',
//     serialNumber: '94-58-cb-a5-cb-9d',
//     manufacturer: 'Unknown',
//     product: 'Joy-Con (R)',
//     release: 1,
//     interface: -1,
//     usagePage: 1,
//     usage: 5,
//     open: [Function: open]
//   }
// ]`

But when I connect my controllers their *product* property is 'Wireless Gamepad'. I can identify Left from Right by it's *productId*.. (8198 = left, 8199 = right)
In this example I connected one left controller (pink) and two right controllers (red and green)
Already tried with blue and red with the same output.

On the windows bluetooth interface I can see them as Joy-Con (L) and Joy-Con (R) but the HID package returns WirelessGamepad.

`[ { vendorId: 1406,
    productId: 8198,
    path:
     '\\\\?\\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002057e_pid&2006#8&1eddca88&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '582f406055c5',
    manufacturer: 'Nintendo',
    product: 'Wireless Gamepad',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 5,
    open: [Function: open] },
  { vendorId: 1406,
    productId: 8199,
    path:
     '\\\\?\\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002057e_pid&2007#8&39eefb17&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '582f405ee802',
    manufacturer: 'Nintendo',
    product: 'Wireless Gamepad',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 5,
    open: [Function: open] },
  { vendorId: 1406,
    productId: 8199,
    path:
     '\\\\?\\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002057e_pid&2007#8&4119924&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: 'b88aec5f72e7',
    manufacturer: 'Nintendo',
    product: 'Wireless Gamepad',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 5,
    open: [Function: open] } ]`

I'm using node v10.15.3
windows 10 pro - 64-bit

**Comment by suchipi** [comment]
Thanks for the detailed issue and investigation! My original testing was on a mac; I tested on windows 10 and I see the same thing you do. I've fixed this in https://github.com/suchipi/switch-joy-con/commit/50fade11f95485c2d1f9e239d5a5113fd30b071c, which has been published as version 1.1.2.
